source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://gitee.com/zhangsen093725/sssu-repo-spec.git'

use_frameworks!

target 'ZSViewUtil_Example' do
  pod 'ZSViewUtil', :path => '../'
end
